apiVersion: 1

datasources:
  - name: Exasol
    type: postgres
    uid: exasol_datasource
    access: proxy
    url: <EXASOL_HOST>:<EXASOL_PORT>
    database: EXA_DB
    user: sys
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1200
      timescaledb: false
    secureJsonData:
      password: '<EXASOL_PASSWORD>'
    isDefault: true
    editable: true
